- name: Install Java
  package:
    name: java
    state: latest

- name: Create Application User
  user: 
    name: "{{APPUSER}}"

- name: Download Tomcat
  unarchive:
    src: "{{TOMCAT_URL}}"
    dest: "/home/{{APPUSER}}"
    remote_src: yes
  become_user: "{{APPUSER}}"

- name: Download StudentApp War file
  get_url:
    url: "{{WAR_URL}}"
    dest: "/home/{{APPUSER}}/apache-tomcat-{{TOMCAT_VERSION}}/webapps"
  become_user: "{{APPUSER}}"

- name: Download JDBC Jar file
  get_url:
    url: "{{JDBC_URL}}"
    dest: "/home/{{APPUSER}}/apache-tomcat-{{TOMCAT_VERSION}}/lib"
  become_user: "{{APPUSER}}"
  

- name: Update Tomcat Context Configuration with Database Details
  templates:
    src: context.xml.j2
    dest: "/home/{{APPUSER}}/apache-tomcat-{{TOMCAT_VERSION}}/conf/context.xml"

# - name: Update Tomcat Context Configuration with Database Details
#   templates:
#     src: context.xml.j2
#     dest: "/home/{{APPUSER}}/apache-tomcat-{{TOMCAT_VERSION}}/conf/context.xml"


- name: Download Tomcat Init script
  get_url:
      url: "{{TOMCAT_INIT_SCRIPT_URL}}"
      dest: /etc/init.d/tomcat
      mode: u=rwx,g=ex,o=rx

- name: Reload Systemctl service
  systemd:
    daemon_reload: yes

- name: Start Tomcat service
  service:
      name: tomcat
      state: restarted




