### Declare a variable  at play and print the value.

- name: Print a variable from play
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: Print a variable 
      debug:
        msg: "URL = {{URL}}"

### Declare a variable at task and print the value.

- name: Print a variable from task
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: Print a variable 
      debug:
        msg: "URL = {{URL}}"
      vars:
        URL: task.google.com 

## What happens if you have same variable in both PLAY and TASK  ??
## Local variables are prioritized in any scripting language , So task variable is going to be the value parsed to task. And always you get vars from task 

## Variable data can be loaded from variable file 

- name: Print values from a file 
  hosts: all 
  vars_files:
    - vars01.yml
  tasks:
    - name: Print a value from Vars File 
      debug:
        msg: URL = {{URL}}

